const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const publicFile = path.join(root, 'data', 'spatial_design_library_public.json');
const masterFile = path.join(root, 'data', 'spatial_design_library_master.json');
const source = JSON.parse(fs.readFileSync(publicFile, 'utf8'));

const configs = {
  'bauhaus-modernist': {name:'Bauhaus / Modernist',subtitle:'İşlevin görünür hâli',summary:'Yapı, kullanım ve üretim mantığının açıkça okunduğu düzenli bir mekânsal sistem.',reading:'Güçlü bir ana eksen, hafif ikincil oturmalar ve açık dolaşım sayesinde oda tek bakışta anlaşılır.',best:'Netlik, doğrudan dolaşım ve amacı görünür nesneler isteyen kullanıcılar.',risk:'Katı simetri gündelik uyarlamayı gereğinden fazla kontrol edebilir.',core:'Sadelik yalnızca azaltma değil; yapı, işlev ve yapım biçimini okunur kılma aracıdır.',spatial:'Oda; eksenler, oranlar ve bağımsız elemanlardan oluşan anlaşılır bir alan olarak kurulur.',empty:'Boşluk işlevleri ayırır, oranı görünür kılar ve nesnelerin birbirine karışmasını engeller.',material:'Çelik, cam, deri, ahşap ve mineral yüzeyler taşıyıcılık ve birleşim mantığını saklamaz.',light:'Işık; düzlemleri, birleşimleri ve dolaşımı açıklığa kavuşturur.',social:'Okunur oturma alanı doğrudan iletişimi desteklerken hareket özgürlüğünü korur.',move:'Bir ana eksen kur; oturma ve masa çizgilerini bu eksene bağla.',furniture:'Görsel olarak hafif iskeletler ve hareketli ikincil elemanlar kullan.',materialMove:'Sınırlı sayıdaki yapısal malzemeyi ve birleşimlerini görünür bırak.',lightMove:'Düzlemleri ve çalışma alanlarını açıklayan katmanlı ışık kullan.',avoid:'Süsleme taklidinden ve gündelik değişimi engelleyen katı simetriden kaçın.',frictions:['belirsiz mekânsal hiyerarşi','zayıf ana eksen','dekoratif fazlalık'],requirements:['açık ana eksen','hafif ikincil oturmalar','disiplinli renk paleti'],contra:['çok dağınık aile kullanımı','yoğun duyusal katman ihtiyacı'],fails:['Her kararı katı simetriye dönüştürmek.','İşlev kurmadan yalnızca krom ve deri görünümü kullanmak.'],personas:{sovereign:'strong',sage:'medium',alchemist:'medium',weaver:'low'}},
  'minimalism': {name:'Minimalizm',subtitle:'Daha az ama daha kesin',summary:'Gereksiz görsel yükü azaltarak her nesnenin işlevini ve yerini belirginleştiren bir yaklaşım.',reading:'Kapalı depolama, az sayıda mobilya ve geniş boşluklar odanın bilişsel yükünü azaltır.',best:'Görsel sakinlik, kolay bakım ve açık bir düzen isteyen kullanıcılar.',risk:'Azaltma uğruna konforu, kişisel belleği veya gerekli depolamayı yok etmek mekânı steril kılabilir.',core:'Her unsurun kalması için açık bir gerekçe bulunmalı; eksiltme kullanım kalitesini güçlendirmelidir.',spatial:'İşlevler az sayıda hacim ve açık aralıklarla tanımlanır.',empty:'Boşluk artık alan değil, düzenin temel bileşenidir.',material:'Az sayıda, sakin ve bakımı anlaşılır malzeme kullanılır.',light:'Yumuşak ve homojen ışık gereksiz görsel kırılmaları azaltır.',social:'Sosyal kullanım korunur fakat nesne ve yüzey kalabalığına dönüşmez.',move:'Önce zorunlu işlevleri yerleştir, sonra gereksiz nesne ve yüzeyleri çıkar.',furniture:'Az sayıda, ölçüsü doğru ve depolama yükünü çözebilen mobilya seç.',materialMove:'Birbiriyle uyumlu iki veya üç ana malzemeyle sınırlı kal.',lightMove:'Parlama yaratmayan dengeli genel ışık ve gerekli görev ışığını birleştir.',avoid:'Boş görünmek uğruna konforu, kimliği ve saklama ihtiyacını ortadan kaldırma.',frictions:['görsel dağınıklık','yüzey taşması','kararsız eşya yerleşimi'],requirements:['kapalı depolama','azaltılmış nesne sayısı','açık dolaşım'],contra:['yoğun koleksiyon sergileme ihtiyacı','çok katmanlı sosyal kullanım'],fails:['Gerekli eşyaları saklayacak sistem kurmadan nesneleri kaldırmak.','Minimalizmi beyaz ve boş görünümle sınırlamak.'],personas:{sovereign:'strong',sage:'strong',alchemist:'low',weaver:'low'}},
  'japanese-minimalism': {name:'Japon Minimalizmi',subtitle:'Aralık, ritüel ve ölçü',summary:'Boşluğu, geçişi ve gündelik ritüeli sakin bir mekânsal düzen içinde ele alan kültürel olarak sınırlı bir yaklaşım.',reading:'Alçak mobilya, açık aralıklar ve belirgin geçişler mekânın yavaş ve dikkatli kullanılmasını destekler.',best:'Ritüel, sakin geçiş ve nesneyle ölçülü ilişki arayan kullanıcılar.',risk:'Japon kültürünü tek bir sade görünüşe indirgemek yüzeysel ve bağlamsız bir taklit üretir.',core:'Mekân; nesneler kadar aralıklar, geçişler ve kullanım ritüelleriyle anlam kazanır.',spatial:'Düşük ağırlık merkezi, katmanlı eşikler ve ölçülü mobilya yoğunluğu kullanılır.',empty:'Boşluk işlevsiz değil; algı, hareket ve duraklama için aktif bir aralıktır.',material:'Doğal malzemeler sessiz birleşimler ve dokunsal yakınlıkla kullanılır.',light:'Süzülmüş ışık, gölge ve yüzey derinliği arasında sakin bir denge kurulur.',social:'Yakınlık ve geri çekilme seçenekleri aynı düzen içinde korunur.',move:'Alçak ve ölçülü elemanlarla belirgin kullanım bölgeleri ve sessiz geçişler kur.',furniture:'Görüş hattını ağırlaştırmayan, kolay taşınabilen ve ritüeli destekleyen parçalar kullan.',materialMove:'Doğal dokuları taklit etmeden, birleşimleri sade ve dürüst tut.',lightMove:'Gün ışığını süz; akşam için düşük seviyeli yerel ışıklar ekle.',avoid:'Kültürel bağlamı yalnızca tatami, paravan veya bej tonlarla temsil etme.',frictions:['hızlı ve kesintili dolaşım','görsel gürültü','ritüelsiz kullanım'],requirements:['açık aralıklar','alçak görsel ağırlık','belirgin eşikler'],contra:['yüksek yoğunluklu depolama','sürekli büyük grup kullanımı'],fails:['Kültürel referansları dekor olarak kopyalamak.','Alçak mobilyanın kullanıcı için erişilebilirliğini kontrol etmemek.'],personas:{sovereign:'medium',sage:'strong',alchemist:'low',weaver:'medium'}},
  'biophilic': {name:'Biyofilik Tasarım',subtitle:'Doğayla ölçülebilir temas',summary:'Gün ışığı, bitki, doğal örüntü ve dışarıyla ilişkiyi kullanıcı deneyimine bağlayan bir performans yaklaşımı.',reading:'Pencere ilişkisi, bitkilerin konumu ve doğal malzemeler görüş, bakım ve dolaşımla birlikte çözülür.',best:'Gün ışığı, dışarıyla bağlantı ve yaşayan unsurlarla ilişki isteyen kullanıcılar.',risk:'Bitki eklemek tek başına biyofilik tasarım değildir; bakım, ışık ve alerji koşulları doğrulanmalıdır.',core:'Doğayla ilişki görsel süs değil; ışık, hava, görüş, malzeme ve zaman deneyiminin bütünüdür.',spatial:'Doğal odaklar ana görüş ve kullanım hatlarıyla ilişkilendirilir.',empty:'Boşluk gün ışığının ve görüşün odada ilerlemesine izin verir.',material:'Doğal veya doğayı çağrıştıran malzemeler dayanım ve bakım kanıtıyla seçilir.',light:'Gün ışığı önceliklidir; parlama ve ısı yükü kontrol edilir.',social:'Doğal odak çevresinde ortak kullanım ve kişisel geri çekilme birlikte desteklenir.',move:'Gün ışığı ve dış görüşü ana kullanım alanlarına bağla; bitkiyi dolaşımdan çıkar.',furniture:'Pencereyi kapatmayan ve bakım erişimi sağlayan alçak, hareketli elemanlar kullan.',materialMove:'Dokunsal doğal malzemeleri dayanım ve bakım koşullarıyla birlikte seç.',lightMove:'Gün ışığını koru; parlama ve akşam karanlık bölgelerini katmanlı ışıkla dengele.',avoid:'Rastgele bitki yoğunluğu, bakımsız canlı malzeme ve kanıtsız sağlık vaadinden kaçın.',frictions:['gün ışığından kopukluk','dış görüşün kapanması','cansız malzeme yoğunluğu'],requirements:['doğrulanmış gün ışığı','bakım erişimi','açık görüş hattı'],contra:['bakım sorumluluğunun belirsizliği','alerji veya evcil hayvan riski'],fails:['Her boş köşeyi bitkiyle doldurmak.','Doğal görünüşü performans kanıtı saymak.'],personas:{sovereign:'medium',sage:'strong',alchemist:'medium',weaver:'strong'}},
  'functional-ergonomic': {name:'İşlevsel / Ergonomik',subtitle:'Göreve ve bedene uyum',summary:'Mekânı gerçek görev, erişim, duruş ve dolaşım gereksinimlerine göre düzenleyen performans yaklaşımı.',reading:'Mobilya, depolama ve geçişler gerçek kullanıcı ölçüleri ve günlük görev dizisiyle sınanır.',best:'Sürtünmeyi azaltmak, çalışmayı kolaylaştırmak ve ölçüye dayalı karar vermek isteyen kullanıcılar.',risk:'Ortalama insan ölçülerini evrensel kabul etmek bireysel farklılıkları ve erişilebilirliği gözden kaçırır.',core:'Biçim, gerçek görev ve kullanıcı gereksinimleriyle sınandığında anlamlıdır.',spatial:'Görev sıraları, erişim bölgeleri ve güvenli dolaşım mekânın ana düzenini belirler.',empty:'Boşluk yaklaşma, dönme, çalışma ve bakım kapasitesidir.',material:'Malzeme seçiminde tutuş, temizlik, yansıma ve dayanım dikkate alınır.',light:'Görev ışığı, ekran parlaması ve görsel konfor kullanım senaryosuna göre ayarlanır.',social:'Ortak kullanımda beden ve görev çatışmaları azaltılır.',move:'Günlük görev sırasını haritala; mobilya ve depolamayı erişim bölgelerine göre yerleştir.',furniture:'Gerçek kullanıcı ölçülerine uygun, ayarlanabilir ve erişimi açık parçalar kullan.',materialMove:'Tutuş, temizlik ve yansıma performansı bilinen yüzeyleri seç.',lightMove:'Görev ışığını çalışma yüzeyine getir; ekran ve gün ışığı parlamasını kontrol et.',avoid:'Standart ölçüyü tek doğru kabul etme; gerçek kullanıcı ve görev testini atlama.',frictions:['zor erişim','çakışan görev sırası','uygunsuz çalışma duruşu'],requirements:['gerçek kullanıcı ölçüsü','görev haritası','doğrulanmış dolaşım'],contra:['ölçüsüz uygulama','yalnızca görsel karar beklentisi'],fails:['Ergonomiyi tek bir standart masa yüksekliğine indirgemek.','Dolaşım ve bakım alanlarını unutmak.'],personas:{sovereign:'strong',sage:'strong',alchemist:'strong',weaver:'medium'}},
  'scandinavian': {name:'İskandinav / Hygge',subtitle:'Işık, sıcaklık ve gündelik ortaklık',summary:'Gün ışığını, sıcak malzemeyi ve rahat ortak kullanımı yalın ama yaşanmış bir düzen içinde birleştirir.',reading:'Yumuşak kenarlı oturma, ortak bir ışık odağı ve açık dolaşım sosyal merkezi güçlendirir.',best:'Samimiyet, paylaşım, gün ışığı ve kolay gündelik bakım isteyen kullanıcılar.',risk:'Hygge kavramını bej tekstil ve mum görünümüne indirgemek kültürel ve işlevsel içeriği zayıflatır.',core:'Yalın işlev, gündelik rahatlık ve toplumsal yakınlık sıcak malzemelerle dengelenir.',spatial:'Oturma elemanları ortak bir merkeze yönelir ve kenarlarda dolaşım korunur.',empty:'Boşluk sosyal yakınlık ile ferahlık arasında ölçülü bir ara verir.',material:'Açık ahşap, yün, keten ve mat yüzeyler bakım koşullarıyla seçilir.',light:'Gün ışığı desteklenir; akşam ışığı düşük seviyeli ve katmanlıdır.',social:'Yüz yüze temas ve ortak masa kullanımı düzenin merkezindedir.',move:'Oturmaları ortak bir merkeze yönelt; çevresinde açık dolaşım bırak.',furniture:'Yumuşak kenarlı, rahat ve ölçeği odaya uygun parçalar kullan.',materialMove:'Açık ahşap ve doğal tekstili temizlenebilirlik ve dayanımla birlikte seç.',lightMove:'Gün ışığını kapatma; akşam için birkaç sıcak ve düşük seviyeli ışık noktası kur.',avoid:'Sadece açık ahşap ve bej renk kullanarak yaklaşımı yüzeysel bir stile dönüştürme.',frictions:['soğuk sosyal atmosfer','yetersiz ortak ışık','dağınık oturma yönleri'],requirements:['sosyal merkez','sıcak ışık katmanları','kolay bakım'],contra:['çok resmî temsil ihtiyacı','yoğun parlak yüzey tercihi'],fails:['Her yüzeyi açık ahşapla kaplamak.','Rahatlığı dolaşımı daraltan büyük mobilyayla karıştırmak.'],personas:{sovereign:'medium',sage:'medium',alchemist:'medium',weaver:'strong'}},
  'organic-architecture': {name:'Organik Mimarlık',subtitle:'Mekân, malzeme ve yerin sürekliliği',summary:'İç mekânı yer, görüş, malzeme ve insan hareketiyle süreklilik içinde kuran bağlamsal yaklaşım.',reading:'Akıcı mobilya çizgileri ve doğal malzeme geçişleri sabit kabuğun sert sınırlarını yumuşatır.',best:'Mekânla bütünlük, akıcı hareket ve malzeme sürekliliği arayan kullanıcılar.',risk:'Kıvrımlı biçim veya doğal malzeme tek başına organik mimarlık oluşturmaz; yerle ilişki gerekir.',core:'Mekân, yapı, malzeme, kullanım ve çevre birbirinden kopuk parçalar değil tek bir sistemdir.',spatial:'Hareket çizgileri ve görüşler keskin bölünmeler yerine süreklilik kurar.',empty:'Boşluk, iç ve dış arasındaki akışı taşıyan bağlayıcı alandır.',material:'Malzemeler yer, yaşlanma ve birleşim mantığıyla birlikte ele alınır.',light:'Gün ışığı hacmin biçimini ve malzeme derinliğini ortaya çıkarır.',social:'Oturma düzeni sert bir cephe yerine akıcı bir ortak alan oluşturur.',move:'Görüş ve hareket hatlarını birbirine bağlayan akıcı bir oturma düzeni kur.',furniture:'Köşeleri yumuşatan ancak dolaşımı belirsizleştirmeyen organik siluetler kullan.',materialMove:'Malzeme geçişlerini rastgele değil, yüzey ve kullanım sürekliliğiyle çöz.',lightMove:'Gün ışığını hacim ve malzeme derinliğini gösterecek biçimde tamamla.',avoid:'Kıvrımlı mobilyayı veya doğal rengi bağlam kurmadan yaklaşımın tamamı sayma.',frictions:['kopuk mekânsal bölgeler','sert dolaşım kırıkları','bağlamsız malzeme'],requirements:['akıcı görüş hattı','malzeme sürekliliği','yerle ilişki'],contra:['çok katı ortogonal temsil','ölçüsüz özel üretim'],fails:['Her nesneyi kıvrımlı seçmek.','Akış uğruna işlevsel sınırları ve depolamayı belirsizleştirmek.'],personas:{sovereign:'low',sage:'medium',alchemist:'strong',weaver:'strong'}},
  'parametric': {name:'Parametrik Tasarım',subtitle:'Değişkenlere bağlı üretim',summary:'Biçim ve yerleşimi tanımlı değişkenler, ilişkiler ve üretim kuralları üzerinden geliştiren yöntem.',reading:'Modüler veya değişken elemanlar farklı kullanım durumlarına ölçülebilir biçimde uyarlanır.',best:'Birden fazla kullanım modu, özel üretim veya değişken koşullar isteyen projeler.',risk:'Karmaşık biçim üretmek parametrik tasarımın amacı değildir; değişkenlerin gerçek ihtiyete bağlanması gerekir.',core:'Tasarım, tek bir sabit sonuç yerine değişkenler ve aralarındaki ilişkilerle tanımlanır.',spatial:'Elemanlar ölçü, kullanım ve üretim kısıtlarına göre uyarlanabilir.',empty:'Boşluk, farklı durumların gerçekleşebilmesi için dönüşüm kapasitesi taşır.',material:'Malzeme ve üretim yöntemi geometrik değişkenlerin sınırlarını belirler.',light:'Açıklık, gölgeleme ve ışık dağılımı ölçülebilir değişkenler olarak ele alınır.',social:'Mekân farklı kişi ve etkinlik sayılarına göre durum değiştirebilir.',move:'Kullanım durumlarını ve değişkenleri tanımla; dönüşebilen elemanları bu kurallara bağla.',furniture:'Modüler, ayarlanabilir veya üretim verisiyle özelleştirilebilir parçalar kullan.',materialMove:'Üretim toleransı ve birleştirme yöntemini biçimden önce doğrula.',lightMove:'Işık, gölge ve açıklık kararlarını ölçülebilir parametrelerle sınayarak ayarla.',avoid:'Yalnızca karmaşık biçim üretmek için gereksiz hesaplama ve özel üretim kullanma.',frictions:['tek kullanıma kilitlenme','değişen kullanıcı sayısı','özel ölçü ihtiyacı'],requirements:['tanımlı değişkenler','üretim toleransı','durum senaryoları'],contra:['düşük bütçeli sabit çözüm','bakım kapasitesinin belirsizliği'],fails:['Parametrik tasarımı kıvrımlı yüzeyle eşitlemek.','Üretim ve bakım maliyetini hesaplamamak.'],personas:{sovereign:'medium',sage:'medium',alchemist:'strong',weaver:'low'}},
  'feng-shui': {name:'Feng Shui Yaklaşımı',subtitle:'Yön, eşik ve ilişkisel düzen',summary:'Yönlenme, eşikler ve mekânsal ilişkileri kültürel bir yorum çerçevesinde ele alan yaklaşım.',reading:'Giriş, ana oturma konumu ve dolaşım hatları görüş güvenliği ve düzen duygusuyla birlikte değerlendirilir.',best:'Yönlenme, eşik ve sembolik mekân ilişkilerine önem veren kullanıcılar.',risk:'Feng Shui bilimsel veya evrensel bir performans standardı gibi sunulmamalıdır.',core:'Mekânın yönleri, eşikleri ve ilişkileri kültürel olarak anlamlandırılmış bir bütün oluşturur.',spatial:'Giriş, ana konum ve hareket çizgileri birbirini gözeten bir düzen içinde ele alınır.',empty:'Boşluk, hareket ve görüşün kesintisiz sürmesi için önemlidir.',material:'Malzeme ve renk seçimleri bağlamsal ve sembolik anlamlarla ilişkilendirilebilir.',light:'Işık, yönlenmeyi ve mekânın dengeli okunmasını destekler.',social:'Ana oturma konumu giriş ve ortak kullanım üzerinde görsel farkındalık sağlar.',move:'Giriş, ana oturma ve hareket hatlarını açık görüş ve güvenli dolaşımla ilişkilendir.',furniture:'Kapıyı ve geçişleri kapatmayan, ana konumu destekleyen yerleşim kullan.',materialMove:'Sembolik seçimleri kullanıcının kültürel yorumu ve gerçek bakım koşullarıyla sınırla.',lightMove:'Karanlık eşikleri azalt; yönlenmeyi destekleyen dengeli ışık kur.',avoid:'Yaklaşımı bilimsel garanti veya tüm kullanıcılar için geçerli kesin kural gibi sunma.',frictions:['girişte yönsüzlük','arkası kapıya dönük ana oturma','kesilen dolaşım'],requirements:['açık eşik','görsel farkındalık','kültürel onay'],contra:['kültürel bağın bulunmaması','ölçüm yerine sembolik kural beklentisi'],fails:['Her kararı sözde enerji akışıyla açıklamak.','Güvenlik ve erişilebilirliği sembolik kurala feda etmek.'],personas:{sovereign:'strong',sage:'medium',alchemist:'medium',weaver:'medium'}},
  'wabi-sabi': {name:'Wabi-Sabi Yaklaşımı',subtitle:'Zaman, kusur ve onarım',summary:'Yaşlanma, iz, onarım ve ölçülü sadeliği kültürel sınırları açık bir tasarım yaklaşımı olarak ele alır.',reading:'Az sayıda dokunsal nesne, sakin boşluk ve onarılabilir malzemeler zamanı görünür kılar.',best:'Kusursuz yüzey yerine yaşanmışlık, bakım ve sessiz malzeme karakteri isteyen kullanıcılar.',risk:'Yıpranmış görünüş üretmek veya bakımsızlığı romantikleştirmek yaklaşımın anlamını bozar.',core:'Geçicilik, kusur ve onarım; nesne ve mekânla daha dikkatli bir ilişki kurar.',spatial:'Az sayıda öğe ve sakin aralıklar malzemenin yaşını ve kullanım izini görünür bırakır.',empty:'Boşluk sessizlik, dikkat ve zaman deneyimi için alan açar.',material:'Doğal yaşlanma ve onarılabilirlik taklit eskitmeden daha değerlidir.',light:'Yumuşak ışık doku ve yüzey değişimini abartmadan gösterir.',social:'Mekân gösterişten çok gündelik yakınlık ve kişisel duraklamayı destekler.',move:'Sakin bir kullanım alanı kur; az sayıda anlamlı ve onarılabilir nesne bırak.',furniture:'Yaşlanması okunur, sağlam ve tamir edilebilir parçalar kullan.',materialMove:'Taklit eskitme yerine gerçek malzeme, bakım ve onarım izini değerlendir.',lightMove:'Dokuyu gösteren yumuşak ve düşük parlamalı ışık kullan.',avoid:'Bakımsızlığı, hasarı veya kültürel simgeleri romantik dekor olarak sunma.',frictions:['kusursuzluk baskısı','geçici moda','onarım yerine değiştirme'],requirements:['onarılabilir malzeme','sakin boşluk','bakım planı'],contra:['yüksek parlaklık beklentisi','kusursuz yüzey talebi'],fails:['Yeni yüzeyi yapay biçimde eskitmek.','İşlev bozukluğunu estetik kabul etmek.'],personas:{sovereign:'low',sage:'strong',alchemist:'medium',weaver:'medium'}},
  'sustainable-circular': {name:'Sürdürülebilir / Döngüsel',subtitle:'Ömür, söküm ve yeniden kullanım',summary:'Malzeme ömrünü, onarımı, sökülebilirliği ve yeniden kullanımı tasarım kararının merkezine alan üretim yaklaşımı.',reading:'Modüler, tamir edilebilir ve bileşenleri ayrılabilir elemanlar değişim ve bakım yükünü azaltır.',best:'Uzun ömür, düşük değiştirme baskısı ve şeffaf malzeme kararı isteyen kullanıcılar.',risk:'Doğal görünüş veya yeşil pazarlama tek başına çevresel performans kanıtı değildir.',core:'Değer, malzemenin kaynağından kullanım ömrü sonrasına kadar korunmalıdır.',spatial:'Yerleşim söküm, onarım, yeniden düzenleme ve bakım erişimini mümkün kılar.',empty:'Boşluk bileşenlerin taşınması, değiştirilmesi ve farklı kullanımlara geçiş için kapasitedir.',material:'İçerik, dayanım, sertifika, onarım ve geri kazanım birlikte değerlendirilir.',light:'Enerji kullanımı kadar bakım ve değiştirilebilirlik de aydınlatma kararına dâhildir.',social:'Uzun ömürlü ortak kullanım ve değişen hane ihtiyaçları desteklenir.',move:'Mevcut olanı koru; yeni elemanları sökülebilir ve yeniden düzenlenebilir kur.',furniture:'Yedek parçası bulunan, tamir edilebilir ve modüler parçalar seç.',materialMove:'Malzeme kaynağı, içerik, bakım ve yaşam sonu bilgisini doğrula.',lightMove:'Verimli, değiştirilebilir ve bakım erişimi açık aydınlatma kullan.',avoid:'Yeşil görünüşü kanıt sayma; sertifika ve yaşam döngüsü kapsamını doğrulamadan iddia kurma.',frictions:['erken değiştirme','bakım erişimsizliği','malzeme belirsizliği'],requirements:['sökülebilir birleşim','onarım planı','doğrulanmış malzeme'],contra:['tek kullanımlık hızlı çözüm','belgesiz çevresel iddia'],fails:['Doğal rengi sürdürülebilirlik kanıtı saymak.','Modüler görünen fakat tamir edilemeyen ürün kullanmak.'],personas:{sovereign:'medium',sage:'strong',alchemist:'strong',weaver:'medium'}},
  'maximalism': {name:'Kontrollü Maksimalizm',subtitle:'Yoğunluk içinde hiyerarşi',summary:'Kişisel ifade, koleksiyon ve desen yoğunluğunu açık bir odak ve düzen sistemi içinde birleştirir.',reading:'Güçlü bir ana odak, gruplanmış koleksiyonlar ve kontrollü renk tekrarları yoğunluğu okunur tutar.',best:'Nesneleri, sanatı ve kişisel hikâyeyi görünür yaşamak isteyen kullanıcılar.',risk:'Her yüzeyi eşit derecede doldurmak yönlenmeyi, bakımı ve dinlenme alanlarını yok eder.',core:'Çokluk rastlantı değildir; kişisel anlatı güçlü bir hiyerarşiyle düzenlenir.',spatial:'Ana odak ve ikincil kümeler yoğun nesne varlığını yönlendirir.',empty:'Boşluk yoğun kompozisyonda dinlenme ve yönlenme alanıdır.',material:'Desen ve malzeme tekrarları renk ve ölçek ilişkileriyle düzenlenir.',light:'Farklı koleksiyon ve kullanım bölgeleri ayrı ışık katmanlarıyla okunur.',social:'Kişisel nesneler sohbet ve aidiyet üretirken oturma ilişkisi korunur.',move:'Bir ana odak belirle; koleksiyonları kümeler hâlinde düzenle ve aralarda sakin alan bırak.',furniture:'Yoğunluğu taşıyacak ölçülü ana parçalar ve düzenli sergileme yüzeyleri kullan.',materialMove:'Renk ve desen tekrarlarını sınırlı bir ilişki sistemi içinde kur.',lightMove:'Ana odak, koleksiyon ve sosyal alan için ayrı ışık katmanları oluştur.',avoid:'Her yüzeyi doldurma; dolaşımı, temizliği ve görsel dinlenmeyi koru.',frictions:['kimliksiz oda','dağınık koleksiyon','zayıf odak'],requirements:['ana odak','gruplanmış sergileme','görsel dinlenme alanı'],contra:['çok düşük bakım kapasitesi','yoğun görsel uyaran hassasiyeti'],fails:['Her boşluğu nesneyle doldurmak.','Koleksiyonları ölçek ve renk ilişkisi kurmadan yaymak.'],personas:{sovereign:'medium',sage:'low',alchemist:'strong',weaver:'strong'}},
  'japandi': {name:'Japandi',subtitle:'Sıcak sadelik ve gündelik dayanım',summary:'Japon ve İskandinav tasarım referanslarını sıcak sadelik, işlev ve dokunsal malzeme etrafında birleştiren çağdaş sentez.',reading:'Alçak görsel ağırlık, kapalı depolama ve sıcak doğal malzemeler sakin ama yaşanabilir bir oda kurar.',best:'Minimal düzen ile sıcaklık arasında denge arayan kullanıcılar.',risk:'Japandi tek bir tarihsel doktrin değildir; bej renk ve açık ahşaba indirgenmemelidir.',core:'Çağdaş bir sentez olarak sadelik, işlev, zanaat ve sıcak gündelik kullanımı birlikte arar.',spatial:'Az sayıda alçak parça, açık dolaşım ve sessiz depolama dengelenir.',empty:'Boşluk hem sakinlik hem gündelik kullanım esnekliği sağlar.',material:'Açık ve koyu ahşap, mat yüzey ve doğal tekstil ölçülü kullanılır.',light:'Süzülmüş gün ışığı ve sıcak yerel ışık katmanları tercih edilir.',social:'Sakinlik korunurken ortak oturma rahat ve erişilebilir kalır.',move:'Kapalı depolama ve alçak mobilyayla sakin bir ana alan kur; sıcak dokuyla dengele.',furniture:'Az sayıda, işlevi açık ve görsel ağırlığı düşük parça kullan.',materialMove:'Ahşap ve doğal tekstili bakım ve dayanımla birlikte seç.',lightMove:'Süzülmüş gün ışığını düşük seviyeli sıcak akşam ışığıyla tamamla.',avoid:'Yaklaşımı yalnızca bej renk, açık ahşap ve dekoratif seramiğe indirgeme.',frictions:['görsel dağınıklık','soğuk minimalizm','yüzey taşması'],requirements:['kapalı depolama','sıcak malzeme','açık dolaşım'],contra:['yoğun koleksiyon sergileme','çok resmî temsil'],fails:['Tüm mekânı tek renk beje çevirmek.','Alçak mobilyanın erişilebilirliğini doğrulamamak.'],personas:{sovereign:'strong',sage:'strong',alchemist:'low',weaver:'medium'}},
  'mid-century-modern': {name:'Yüzyıl Ortası Modernizmi',subtitle:'İnsan ölçeği ve görsel hafiflik',summary:'Savaş sonrası modern üretim açıklığını sıcak malzeme, insan ölçeği ve hafif mobilyayla birleştirir.',reading:'Alçak ve ayaklı mobilyalar açık bir sohbet alanı kurarken zeminin ve dolaşımın okunmasını sağlar.',best:'Sosyal sıcaklık, dayanıklı biçim ve görsel hafiflik isteyen kullanıcılar.',risk:'İkonik parçaları ölçü ve dolaşım çözmeden toplamak odayı dönem dekoruna dönüştürür.',core:'Endüstriyel üretim gündelik yaşam için insancıl, açık ve sıcak nesnelere çevrilir.',spatial:'Alçak mobilya, görünür zemin ve açık sosyal açı oda içinde ferah bir merkez oluşturur.',empty:'Mobilyalar arasındaki açıklık esneklik ve görsel hafiflik sağlar.',material:'Ceviz veya tik, deri, yün, cam ve metal açık konstrüksiyonla kullanılır.',light:'Yerel sıcak lambalar gün ışığını tamamlar ve küçük kullanım bölgeleri kurar.',social:'Koltuklar kompakt bir masa çevresinde yüz yüze ilişki kurar.',move:'Alçak, ayaklı ve insan ölçeğinde mobilyalarla açık bir sohbet alanı kur.',furniture:'Kompakt oturma, görünür ayaklar ve hareketli yan koltuklar kullan.',materialMove:'Sıcak ahşap, deri veya yünü küçük metal ve cam dokunuşlarla dengele.',lightMove:'Bir veya iki yerel sıcak ışıkla sosyal alanı tanımla.',avoid:'Dönem ikonlarını ölçüsüz toplama; kullanıcının oturma yüksekliğini doğrula.',frictions:['ağır mobilya yoğunluğu','zayıf sosyal açı','dönemsel dekor taklidi'],requirements:['insan ölçeği','görsel hafiflik','açık sohbet düzeni'],contra:['çok yüksek depolama ihtiyacı','çok resmî simetri'],fails:['İkonik mobilyayı plan çözümü sanmak.','Alçak oturmanın kullanıcıya uygunluğunu kontrol etmemek.'],personas:{sovereign:'medium',sage:'medium',alchemist:'medium',weaver:'strong'}},
  'art-deco': {name:'Art Deco',subtitle:'Geometri ve ölçülü ihtişam',summary:'Geometrik düzeni, nitelikli zanaatı ve kontrollü karşıtlığı işlevle birleştiren tarihsel tasarım dili.',reading:'Belirgin eksen, kıvrımlı oturma ve az sayıda parlak odak mekâna tören duygusu kazandırır.',best:'Karşıtlık, simetri, zanaat ve güçlü temsil isteyen kullanıcılar.',risk:'Parlak yüzey, metal ve motif fazlalığı ölçeği, konforu ve bakımı zorlaştırabilir.',core:'Art Deco modern geometriyi, makine çağının imgelerini ve yüksek zanaat niteliğini bir araya getirir.',spatial:'Güçlü bir eksen ve dengeli kıvrımlar mekânı törensel fakat kullanılabilir kılar.',empty:'Boşluk, zengin yüzeylerin ve güçlü siluetlerin birbirine karışmasını önler.',material:'Nitelikli ahşap, cam, taş ve metal seçici ve bakım bilgisiyle kullanılır.',light:'Sıcak katmanlı ışık yüzey derinliğini ve metal ayrıntıyı parlamaya dönüştürmeden gösterir.',social:'Biçimsel olarak düzenli oturma grubu güçlü bir karşılama ve sohbet alanı kurar.',move:'Bir ana eksen kur; kıvrımlı oturma ve birkaç geometrik odakla kullanımı çerçevele.',furniture:'Konforlu ve belirgin siluetli parçaları dolaşımdan uzak düzenle.',materialMove:'Bir zengin ahşap veya taş, bir metal vurgu ve sakin tekstil kullan.',lightMove:'Yüzey derinliğini gösteren sıcak, kontrollü ve düşük parlamalı ışık kur.',avoid:'Altın-siyah dekor klişesine, aşırı parlaklığa ve bakım yüküne düşme.',frictions:['temsilsiz giriş','zayıf eksen','dağınık lüks görünümü'],requirements:['ana eksen','seçici parlaklık','nitelikli zanaat'],contra:['çok düşük bakım kapasitesi','yüksek duyusal hassasiyet'],fails:['Art Deco’yu altın renkli aksesuar sanmak.','Simetri uğruna günlük uyarlamayı engellemek.'],personas:{sovereign:'strong',sage:'low',alchemist:'medium',weaver:'medium'}},
  'brutalism': {name:'Brütalizm',subtitle:'Kütle, yapı ve doğrudanlık',summary:'Kütle, strüktür ve malzeme ifadesini güçlü fakat yaşanabilir bir mekânsal düzen içinde ele alır.',reading:'Az sayıda ağır hacim merkezi tanımlarken geniş boş kenarlar ve dokunsal yüzeyler sertliği dengeler.',best:'Yapısal açıklık, dayanıklı malzeme ve düşük görsel gürültü isteyen kullanıcılar.',risk:'Konfor ve akustik çözmeden beton görünümü kopyalamak soğuk bir imge üretir.',core:'Brütalizm burada beton görünümü değil, yapı ve malzemenin doğrudan okunması olarak ele alınır.',spatial:'Ağır hacimler güçlü bir merkez kurarken çevresinde açık dolaşım bırakılır.',empty:'Boşluk kütleyi dengeler ve yönlenmeyi korur.',material:'Mineral yüzey, ahşap, deri ve metal ağırlık ve birleşim mantığını açıkça gösterir.',light:'Yönlü ışık dokuyu ortaya çıkarır; mekân gereksiz karanlığa bırakılmaz.',social:'Kararlı oturma elemanları doğrudan bir ortak alan kurar.',move:'Az sayıda güçlü kütleyle merkezi tanımla; çevresinde geniş dolaşım bırak.',furniture:'Sağlam blok formlar ile dokunsal ve taşınabilir koltukları dengele.',materialMove:'Mineral veya koyu metal yüzeyi sıcak ahşap, deri ve emici tekstille dengele.',lightMove:'Dokuyu gösteren yönlü ışığı rahat genel ışıkla birleştir.',avoid:'Sahte beton, sığınak karanlığı ve yaklaşım alanını daraltan ağır mobilyadan kaçın.',frictions:['zayıf mekânsal ağırlık','fazla küçük nesne','yapısal belirsizlik'],requirements:['okunur kütle','açık dolaşım','sıcak karşıtlık'],contra:['dar yaklaşım alanı','sert akustik koşul'],fails:['Beton görünümünü yaklaşımın tamamı saymak.','Konfor ve erişilebilirliği anıtsal biçme feda etmek.'],personas:{sovereign:'strong',sage:'medium',alchemist:'medium',weaver:'low'}},
  'postmodernism': {name:'Postmodernizm',subtitle:'Çoğul referans ve kontrollü oyun',summary:'Tek doğru modernist cevabı sorgulayan; renk, alıntı, çelişki ve mizahı kullanan çoğul tasarım dili.',reading:'Sakin bir temel, belirgin geometrik nesneleri ve kontrollü rengi planı kaybetmeden taşır.',best:'Kişisel ifade, kültürel referans ve biçimsel çeşitlilik isteyen kullanıcılar.',risk:'Düzenlenmemiş yenilik, desen ve ironi hiyerarşiyi silerek yorucu bir mekân yaratabilir.',core:'Postmodernizm saflık yerine karmaşıklık, çelişki ve tarihsel alıntıya alan açar.',spatial:'Sabit dolaşım düzeni farklı biçim, renk ve referansları birlikte taşır.',empty:'Boşluk çoğulluğu düzenler ve kalabalığa dönüşmesini önler.',material:'Sıradan ve nitelikli yüzeyler bilinçli karşıtlık içinde yan yana gelebilir.',light:'Işık renk ve silueti ayırır; her nesneyle yarışan gösteriye dönüşmez.',social:'Farklı oturma karakterleri ifade ve sohbet seçenekleri oluşturur.',move:'Planı sade tut; birkaç farklı biçim ve rengi okunur ifade noktaları olarak ekle.',furniture:'Nötr ve rahat ana parçaları iki veya üç ifade gücü yüksek taşınabilir parçayla birleştir.',materialMove:'Mat-parlak ve sıradan-nitelikli karşıtlığını sınırlı palet içinde kur.',lightMove:'Renk ve silueti okunur kılan dengeli ışık kullan.',avoid:'Yenilik yığını, rastgele tarihsel alıntı ve konforsuz ifade mobilyasından kaçın.',frictions:['kimlik eksikliği','tekdüze modernizm','ifadesiz renk düzeni'],requirements:['sakin temel','çoğul odak','kontrollü renk'],contra:['yüksek görsel uyaran hassasiyeti','çok katı kurumsal düzen'],fails:['Postmodernizmi rastgele maksimalizm sanmak.','Tek bir Memphis motifini mekânsal fikir yerine kullanmak.'],personas:{sovereign:'low',sage:'low',alchemist:'strong',weaver:'strong'}},
  'industrial-adaptive-reuse': {name:'Endüstriyel / Uyarlanabilir Yeniden Kullanım',subtitle:'Yıkmadan önce yeniden değerlendir',summary:'Mevcut değeri, onarımı ve tersine çevrilebilir birleşimleri temalı endüstriyel görünümün önüne koyan üretim yaklaşımı.',reading:'Yeniden kullanılan ahşap, metal iskelet ve modüler depolama sahte mimari tarih üretmeden esnek bir düzen kurar.',best:'Dayanım, görünür onarım ve daha düşük değiştirme baskısı isteyen kullanıcılar.',risk:'Sahte tuğla, dekoratif boru ve yapay eskitme yeniden kullanım kanıtı değildir.',core:'Uyarlanabilir yeniden kullanım mevcut değeri korur ve yeni müdahaleyi sökülebilir, onarılabilir kılar.',spatial:'Modüler ve dayanıklı elemanlar mevcut koşullara uyum sağlar.',empty:'Açık çalışma alanı mobilyanın taşınmasına, onarımına ve yeni duruma geçmesine izin verir.',material:'Yeniden kullanılan ahşap ve metal, güvenlik ve bakım doğrulamasıyla geçmişini görünür bırakır.',light:'Ayarlanabilir ve tersine çevrilebilir aydınlatma değişen kullanıma eşlik eder.',social:'Taşınabilir parçalar ortak kullanım, çalışma ve sakin duruma geçiş sağlar.',move:'Mevcut kullanılabilir unsurları koru; tamir edilebilir ve modüler mobilya ekle.',furniture:'Yedek parçası bulunan, sökülebilen ve taşınabilen iskeletler seç.',materialMove:'Güvenliği doğrulanmış yeniden kullanılan veya dayanıklı malzeme kullan.',lightMove:'Sökülebilir, ayarlanabilir görev ve genel ışığı birlikte kur.',avoid:'Sahte patina, dekoratif boru ve güvenliği belirsiz çıkma malzemeden kaçın.',frictions:['gereksiz yenileme','tek kullanımlık mobilya','onarım erişimsizliği'],requirements:['mevcut değer envanteri','sökülebilir birleşim','güvenlik doğrulaması'],contra:['belgesiz çıkma malzeme','gelecekte değişemeyen sabit kurgu'],fails:['Endüstriyel görünümü yeniden kullanım kanıtı saymak.','Ağır sabit elemanlarla uyarlanabilirliği engellemek.'],personas:{sovereign:'medium',sage:'medium',alchemist:'strong',weaver:'medium'}},
  'universal-inclusive': {name:'Evrensel / Kapsayıcı Tasarım',subtitle:'Seçenek, açıklık ve geniş kullanılabilirlik',summary:'Kaçınılabilir engelleri; eşit kullanım, esneklik, sezgisel düzen, düşük çaba ve yeterli yaklaşım alanıyla azaltan performans çerçevesi.',reading:'Sağlam oturma, yuvarlatılmış kenar, ton farkı ve geniş yollar farklı beden ve rutinleri klinik görünmeden destekler.',best:'Paylaşılan evler, değişen gereksinimler ve düşük çabalı gündelik kullanım.',risk:'Tek çözümü evrensel ilan etmek bireysel gereksinimleri gizler; doğrudan kullanıcı kanıtı gerekir.',core:'Ürün ve çevreler mümkün olduğunca çok kişi tarafından özel uyarlama gerektirmeden kullanılabilmelidir.',spatial:'Anlaşılır yollar, yeterli yaklaşım alanı ve farklı kullanım seçenekleri önceliklidir.',empty:'Boşluk yaklaşma, dönme, yardım ve gelecekteki değişim kapasitesidir.',material:'Düşük parlama, kolay bakım ve yeterli ton farkı kenarları okunur kılar.',light:'Dengeli genel ışık, ayarlanabilir görev ışığı ve parlama kontrolü farklı görsel gereksinimleri destekler.',social:'Farklı oturma konumları insanları ayırmadan katılım seçeneği sunar.',move:'Geniş ve okunur yolları koru; farklı destek seviyelerinde oturma seçenekleri ekle.',furniture:'Kolçaklı, sağlam, yuvarlatılmış ve kenarları okunur parçalar kullan.',materialMove:'Düşük parlamalı, kolay bakımlı ve yeterli ton farkı olan yüzeyler seç.',lightMove:'Dengeli genel ışığı ayarlanabilir görev ışığı ve parlama kontrolüyle tamamla.',avoid:'Simgesel erişilebilirlik jesti, dengesiz alçak oturma ve ölçüsüz iddiadan kaçın.',frictions:['dar yaklaşım alanı','yüksek fiziksel çaba','okunmayan kenarlar'],requirements:['ölçülü yaklaşım alanı','farklı kullanım seçeneği','düşük çaba'],contra:['kullanıcı görüşünün alınmaması','ölçüsüz standart çözüm'],fails:['Kapsayıcılığı klinik görünümle eşitlemek.','Tek çözümün herkese uyacağını varsaymak.'],personas:{sovereign:'strong',sage:'strong',alchemist:'medium',weaver:'strong'}},
  'sensory-regulated': {name:'Duyusal Düzenlemeli Tasarım',subtitle:'Öngörülebilir bölgeler ve ayarlanabilir uyaran',summary:'Uyaranı daha öngörülebilir ve ayarlanabilir kılmak için bölgeleme, geri çekilme seçeneği, akustik yumuşaklık ve parlama kontrolü kullanan ihtiyatlı çerçeve.',reading:'Sakin sosyal bölge ile daha düşük uyaranlı bir koltuk birlikte çalışır; kapalı depolama ve katmanlı ışık görsel yükü azaltır.',best:'Öngörülebilir düzen, görsel sakinlik ve uyaran seviyesini seçme ihtiyacı olan kullanıcılar.',risk:'Duyusal gereksinimler kişiseldir; yaklaşım tedavi veya evrensel otizm çözümü gibi sunulamaz.',core:'Duyusal düzenleme kaçınılabilir belirsizliği azaltır ve kullanıcıya kontrol seçeneği verir; tanı veya tedavi değildir.',spatial:'Açık bölgeler, geçişler ve bağlantılı bir geri çekilme noktası mekânı öngörülebilir kılar.',empty:'Dağınıklıktan arındırılmış aralıklar etkinlikler arasındaki geçişi açıklığa kavuşturur.',material:'Mat, dokunsal ve akustik açıdan yumuşak yüzeyler kullanıcı tercihiyle sınanır.',light:'Katmanlı, kısılabilir ve düşük parlamalı ışık şiddet seçeneği sunar.',social:'Farklı katılım mesafeleri katılma, duraklama veya geri çekilme seçeneği sağlar.',move:'Sosyal ve düşük uyaranlı konumları ayır; kapalı depolama ve öngörülebilir dolaşım kur.',furniture:'Geleneksel sosyal oturma ile bağlantılı bir geri çekilme koltuğunu birlikte sun.',materialMove:'Mat, akustik açıdan yumuşak ve düşük kokulu malzemeyi kullanıcıyla doğrula.',lightMove:'Kısılabilir, dolaylı ve düşük parlamalı birkaç ışık seviyesi kur.',avoid:'Otizme özgü tek tip estetik, tıbbi ekipman imgesi ve sakinlik garantisinden kaçın.',frictions:['öngörülemeyen uyaran','parlama ve yankı','geri çekilme seçeneği eksikliği'],requirements:['belirgin bölgeler','ayarlanabilir ışık','bağlantılı geri çekilme noktası'],contra:['kullanıcı tercihi olmadan reçete','tedavi iddiası'],fails:['Sessiz rengi duyusal çözüm sanmak.','Kullanıcıyı sosyal alandan tamamen ayırmak.'],personas:{sovereign:'medium',sage:'strong',alchemist:'medium',weaver:'medium'}}
};

const roomData = {
  living_room:{label:'Oturma odası',intent:'Toplanma, geri çekilme ve medya kullanımını ana dolaşımı bozmadan desteklemek.',extra:'Sohbet mesafesini, televizyon görüşünü ve yaklaşım yollarını doğrula.',light:'Genel, görev ve düşük seviyeli akşam ışığını birlikte sınayarak ekran parlamasını kontrol et.',success:'Kullanıcılar ana mobilyayı taşımadan toplanabilir, televizyon izleyebilir, geri çekilebilir ve odadan geçebilir.'},
  kitchen:{label:'Mutfak',intent:'Hazırlık, pişirme, temizlik, depolama ve ortak kullanımı güvenli bir sıra hâline getirmek.',extra:'Erişim, tezgâh, cihaz açılımı, iniş alanı ve kesişen kullanıcı yollarını doğrula.',light:'Çalışma yüzeylerine kontrollü görev ışığı verirken ortak kullanım için rahat genel ışığı koru.',success:'Günlük yemek dizisi tekrarlanan uzanma, kapak çakışması veya geçiş engeli olmadan tamamlanır.'},
  bedroom:{label:'Yatak odası',intent:'Uyku, toparlanma, giyinme ve kişisel depolamayı gereksiz duyusal ve dolaşım baskısından korumak.',extra:'Yatağa yaklaşım, başucu erişimi, dolap açılımı ve düşük uyaranlı akşam durumunu doğrula.',light:'Düşük akşam ışığı, okuma ışığı ve gün ışığı kontrolünü ayır.',success:'Odaya giriş, uyku, uyanma ve giyinme engel, parlama veya eşya taşması olmadan gerçekleşir.'},
  studio:{label:'Stüdyo',intent:'Kompakt bir kabuğun depolama ve dolaşımı kaybetmeden farklı durumlara geçmesini sağlamak.',extra:'Gündüz, çalışma, sosyal ve uyku durumlarını adlandır; dönüşen her parçanın saklama yerini belirle.',light:'Kalıcı bölme kullanmadan durumları ayıran değiştirilebilir ışık katmanları kur.',success:'Her durum hızlıca kurulup kullanılabilir ve artık dağınıklık bırakmadan geri toplanır.'},
  home_office:{label:'Ev ofisi',intent:'Uzun süreli çalışmayı, ekipman erişimini ve odağı açıp kapatma ritüelini desteklemek.',extra:'Duruş değişimi, ekran konumu, kablo yolu, görev erişimi, depolama ve akustik etkileri doğrula.',light:'Gün ışığı, ekran parlaması ve ayarlanabilir görev ışığını dengele.',success:'Tam bir çalışma oturumu geçici kablolama, tekrarlanan uzanma veya dolaşım kesintisi olmadan tamamlanır.'},
  terrace:{label:'Teras',intent:'İklim, bakım, eşik ve dış ortam koşullarına uygun gerçek bir kullanım alanı oluşturmak.',extra:'Kapı açılımı, drenaj, rüzgâr, gölge, bitki bakımı, mobilya saklama ve açık yolu doğrula.',light:'Komşuluk ve eşik güvenliğini koruyan düşük parlamalı dış ortam ışığı kullan.',success:'Alan hedeflenen mevsimlerde rahat, güvenli, drenajlı ve bakımı yapılabilir kalır.'}
};

const categoryLabels = {
  historical_expression:['Tarihsel ifade','Tarihsel bir çizginin güncel mekânsal kararlara çevrilmesi.'],
  performance_framework:['Performans çerçevesi','Konfor, işlev, iyilik hâli veya ölçülebilir kullanımla yönlenen yöntem.'],
  production_method:['Üretim yöntemi','Bileşenlerin üretilme, birleştirilme ve uyarlanma biçimiyle şekillenen yaklaşım.'],
  cultural_symbolic:['Kültürel / simgesel','Anlamı evrensel bilim gibi sunulmaması gereken kültürel olarak sınırlı yaklaşım.'],
  market_synthesis:['Çağdaş sentez','Yön bulmak için yararlı fakat tek bir tarihsel doktrin olmayan çağdaş birleşim.']
};

const sourceTopics = {
  'bauhaus-programme':'Bauhaus düşüncesi ve eğitim programı','sullivan':'Biçim ve işlev ilişkisi','pawson-minimum':'Mekânsal minimum düşüncesi','nielsen_norman_minimalism':'Minimalizmin kullanılabilirlik sınırları','met-japanese-tea':'Japon çay töreni ve mekân düzeni','met-wabisabi':'Wabi-Sabi ve çay kültürü','terrapin-14':'Biyofilik tasarım örüntüleri','who-housing-health':'Konut ve sağlık kılavuzu','dreyfuss':'İnsan ölçüsü ve endüstriyel tasarım','iso-9241-11':'Kullanılabilirlik tanımları','vam-scandinavian-context':'İskandinav tasarımının tarihsel bağlamı','wright':'Organik mimarlık düşüncesi','wbdg-passive':'Pasif güneş tasarımı','passivehouse':'Yapı performansı ve sertifikasyon','eu-circular':'Döngüsel ekonomi eylem planı','fengshui-xu':'Feng Shui ve avlulu konut düzeni','fengshui-review':'Feng Shui ile çevre psikolojisinin eleştirel karşılaştırması','parametricism':'Parametrik tasarımın kuramsal çerçevesi','vam-maximalism':'Maksimalist iç mekânların tarihsel bağlamı','knoll-barcelona-chair':'Barcelona Koltuğu ve pavyon bağlamı','cooperhewitt-breuer':'Marcel Breuer ve çelik boru mobilya','met-shoin-room':'Shōin odasının mekânsal yapısı','met-ma-in-between':'Ma kavramı ve aralık düşüncesi','moma-bone-chair':'Bone Chair ve hesaplamalı üretim','louis-poulsen-ph':'PH aydınlatma sistemi ve kamaşma kontrolü','carlhansen-ch24':'CH24 koltuğu, birleşim ve üretim','muji-philosophy':'MUJI üretim ve sadeleştirme ilkeleri','c2c-standard-v5':'Döngüsel ürün değerlendirme standardı','moma-good-design':'Savaş sonrası İyi Tasarım programı','vam-art-deco':'Art Deco’nun tarihsel kaynakları','riba-brutalism':'Brütalizmin kökeni ve yapısal doğrudanlığı','vam-postmodernism':'Postmodernizmin tasarım tarihindeki yeri','epa-adaptive-reuse':'Mevcut yapıların uyarlanarak yeniden kullanımı','ncsu-universal-design':'Evrensel Tasarımın yedi ilkesi','mostafa-aspectss':'Duyusal tasarım ve ASPECTSS çerçevesi'
};

const comparisonSets = {
  'quiet-space-differences':['Aynı sakinlik isteği, farklı mekânsal nedenler','Projede “sakinlik” hangi davranış ve sürtünmeyi ifade ediyor?','Depolama, ritüel, duyusal tolerans, sosyal sıcaklık ve zamanla ilişkiyi karşılaştır; yalnızca görüntüye göre seçim yapma.'],
  'nature-differences':['Doğa bağlantısı ve yerle bütünleşme','Projede görsel doğa teması mı, yapısal yer ilişkisi mi gerekli?','Bitki, gün ışığı ve dış görüş ile yer, malzeme ve yapı sürekliliğini birbirine karıştırma.'],
  'logic-differences':['İşlev, yapım ve hesaplama','Kararı görev, konstrüksiyon veya değişken üretimden hangisi yönlendiriyor?','İşlevsel uyum, yapım açıklığı ve parametrik değişkenler ayrı gerekçe ister.'],
  'expression-differences':['Kontrollü kimlik ve kültürel düzen','Kullanıcı kişisel ifade mi, simgesel yönlenme mi arıyor?','Yoğun ifade ile kültürel olarak sınırlı mekân düzenini aynı kanıt düzeyinde sunma.'],
  'historical-expression-differences':['Tarihsel ifade içinde farklı düzenler','Her tarihsel yaklaşım hiyerarşiyi nasıl kuruyor?','İnsan ölçeği, törensel eksen, yapısal kütle ve çoğul ifadeyi yalnızca renk paletine göre seçme.'],
  'inclusive-performance-differences':['Geniş kullanılabilirlik ve duyusal seçenek','Proje hangi engeli azaltmaya çalışıyor?','Ergonomik uyum, kapsayıcı kullanılabilirlik ve duyusal düzenleme örtüşebilir fakat birbirinin yerine geçmez.'],
  'reuse-production-differences':['Daha düşük etkili üretim için farklı yollar','Öncelik koruma, döngüsellik veya uyarlanabilir üretim mi?','Mevcudu koruma, malzeme döngüsü ve değişken üretim farklı tedarik ve doğrulama ister.']
};

function levelText(value) {
  return {strong:'güçlü',medium:'orta',low:'düşük'}[value] || value;
}

function roomApplications(config) {
  return Object.fromEntries(Object.entries(roomData).map(([id, room]) => [id, {
    move:config.move,
    basis:'editoryal_ceviri',
    requires_measurement:true,
    verification:'Uygulamadan önce geometri, dolaşım, erişim, bakım, kullanıcı rutini ve duyusal tercih doğrulanmalıdır.',
    intent:room.intent,
    furniture_direction:`${config.furniture} ${room.extra}`,
    material_direction:config.materialMove,
    lighting_direction:`${config.lightMove} ${room.light}`,
    avoid:`${config.avoid} Görsel yaklaşımın güvenlik, erişim, bakım veya farklı kullanım durumlarını geçersiz kılmasına izin verme.`,
    success_test:room.success,
    evidence_status:'editoryal_ceviri',
    project_checks:['doğrulanmış geometri','kullanıcı rutini ve tercihi','erişilebilirlik','bakım ve onarım','ışık, akustik ve duyusal konfor']
  }]));
}

function lensRecord(lens) {
  const c = configs[lens.slug];
  if (!c) throw new Error(`Türkçe yapılandırma eksik: ${lens.slug}`);
  const compatible = source.lenses.filter(item => item.slug !== lens.slug && item.category === lens.category).slice(0,3).map(item=>item.slug);
  const tensions = source.lenses.filter(item => item.slug !== lens.slug && item.category !== lens.category).slice(-2).map(item=>item.slug);
  const levers = [
    {name:'Ana mekânsal hamle',abstract:c.move,concrete:c.move,success_test:'Ana kullanım ve dolaşım tek bakışta okunuyor.'},
    {name:'Mobilya mantığı',abstract:c.furniture,concrete:c.furniture,success_test:'Mobilya gerçek kullanıcıya ve ölçülen odaya uyuyor.'},
    {name:'Malzeme ve ışık',abstract:`${c.materialMove} ${c.lightMove}`,concrete:`${c.materialMove} ${c.lightMove}`,success_test:'Malzeme, bakım ve ışık koşulları birlikte doğrulandı.'}
  ];
  const claims = [
    {id:`${lens.slug}-baglam`,text:c.summary,type:'tasarim_baglami',status:'destekli',source_refs:lens.source_refs,scope:'Tarihsel veya yöntemsel bağlamı açıklar; kişilik tanısı değildir.',public_safe:true},
    {id:`${lens.slug}-oda-cevirisi`,text:c.reading,type:'editoryal_cikarim',status:'editoryal_ceviri',source_refs:lens.source_refs,scope:'Sabit kavramsal oda için PersonaLayouts yorumudur; ölçülmüş proje sonucu değildir.',public_safe:true},
    {id:`${lens.slug}-sinir`,text:c.risk,type:'risk_siniri',status:'dogrulama_gerekli',source_refs:lens.source_refs,scope:'Müşteri kanıtı, ölçülmüş geometri ve ilgili standartlarla doğrulanmalıdır.',public_safe:true}
  ];
  return {
    ...lens,
    name:c.name,subtitle:c.subtitle,
    public:{
      summary:c.summary,room_reading:c.reading,best_for:c.best,watch_for:c.risk,levers,
      method_note:'Editoryal tasarım çevirisidir; davranış kanıtı, kullanıcı tercihi ve doğrulanmış proje koşullarıyla uyarlanmalıdır.',
      room_applications:roomApplications(c),
      philosophy:{core:c.core,spatial_why:c.spatial,role_of_empty_space:c.empty,material_logic:c.material,light_logic:c.light,social_logic:c.social},
      not_to_confuse_with:[`${c.name}, yalnızca renk veya dekor öğeleriyle tanımlanamaz.`,c.avoid],
      reference_ids:lens.public.reference_ids
    },
    admin:{
      status:'onayli',persona_support:c.personas,frictions:c.frictions,requirements:c.requirements,contraindications:c.contra,
      requires_measurement:['dolaşım açıklığı','yaklaşım ve erişim mesafeleri','ana mobilya ölçüleri'],source_refs:lens.source_refs,
      claim_caution:'Bu yaklaşım bir kişilik tanısı veya otomatik proje reçetesi değildir.',claims,failure_modes:c.fails,
      hybrid_relations:{compatible,tensions},context_rule:'Yalnızca kanıt → sürtünme → persona ve mekânsal imza sırası kurulduktan sonra seç. Uygulamadan önce geometri, erişilebilirlik, iklim, bütçe ve bakımı doğrula.'
    }
  };
}

const master = {
  version:'4.0.0-tr',updated_at:'2026-08-17',
  publication:{
    evidence_boundary:'Atlas; tarihsel bağlamı, standartları ve editoryal mekân çevirilerini birbirinden ayırır. Ölçüye bağlı kararlar gerçek projede doğrulanmadan kesin hüküm değildir.',
    persona_boundary:'Bir tasarım yaklaşımı persona tanısı değildir. Persona seçimi davranış kanıtı ve proje bağlamı gerektirir.',
    public_projection:'Public Atlas yalnızca onaylı ve sınırları yazılmış içeriği kullanır.'
  },
  scene:{...source.scene,fixed_variables:['kamera konumu, yüksekliği, perspektif ve kadraj','oda oranları ve tavan çizgisi','üç parçalı siyah doğramalı pencere ve dış görünüş','sağ duvardaki niş ve televizyon konumu','meşe zemin yönü ve temel gün ışığı']},
  taxonomy:source.taxonomy.map(item=>({id:item.id,label:categoryLabels[item.id][0],description:categoryLabels[item.id][1]})),
  sources:source.sources.map(item=>{const topic=sourceTopics[item.id]||'Tasarım araştırması';return {...item,label:`${item.author} — ${topic}`,claim_scope:`Bu kaynak ${topic.toLocaleLowerCase('tr-TR')} konusunda tarihsel, kurumsal veya araştırmaya dayalı bağlam sağlar.`,limitations:'Tek başına evrensel bir iç mekân reçetesi veya kullanıcı sonucu kanıtlamaz; proje çevirisi ayrıca doğrulanmalıdır.'}}),
  lenses:source.lenses.map(lensRecord),
  research_governance:{
    reference_rule:'Referanslar zorunlu satın alma listesi değil; ilkeyi ve tarihsel bağlamı açıklayan sınırlı örneklerdir.',
    public_claim_quarantine:['sağlık sonucu garantileri','enerji performansı garantileri','ergonomik uygunluk garantileri','kültürel yaklaşımı evrensel bilim gibi sunan ifadeler','ölçülmemiş projeye ait kesin ölçü kararları']
  },
  rooms:Object.entries(roomData).map(([id,item])=>({id,label:item.label,status:id==='living_room'?'gorsel_ve_protokol':'yalnizca_protokol'})),
  reference_registry:source.reference_registry.map(ref=>{const c=configs[ref.lens];return {...ref,principle:c?c.core:'Bu kayıt yaklaşımın ilkesini tarihsel bir örnek üzerinden görünür kılar.',use_as:'Tarihsel veya yöntemsel referans olarak kullan; zorunlu ürün ya da doğrudan satın alma önerisi değildir.'}}),
  comparison_sets:source.comparison_sets.map(set=>{const tr=comparisonSets[set.id];return {...set,label:tr[0],question:tr[1],decision_note:tr[2]}}),
  hybrid_framework:{
    selection_rule:'Birincil yaklaşım ana sürtünmeyi çözmeli; destekleyici yaklaşım eksik performansı tamamlamalıdır. Görsel benzerlik tek başına seçim nedeni değildir.',
    persona_boundary:'Persona davranış örüntüsünü, Atlas yaklaşımı ise tasarım mantığını açıklar. Biri diğerinin yerine kullanılamaz.',
    conflict_test:['İki yaklaşım aynı dolaşım alanını farklı biçimde mi kullanıyor?','Malzeme ve bakım beklentileri birbiriyle çelişiyor mu?','Sosyal yakınlık ile geri çekilme ihtiyacı dengeleniyor mu?','Seçilen yaklaşım ölçü, bütçe ve uygulama kapasitesine uyuyor mu?']
  },
  local_context:{
    id:'turkiye-konut-baglami',label:'Türkiye konut bağlamı',public_boundary:'Yerel iklim, yapı stoğu, zanaat, tedarik, yönetmelik ve hane rutini doğrulanmadan hiçbir yaklaşım doğrudan uygulanmaz.',
    checks:['iklim ve yönlenme','mevcut yapı ve tesisat','yerel malzeme ve zanaat','tedarik ve bakım kapasitesi','yangın ve erişilebilirlik koşulları','hane rutini ve kültürel tercih'],suggested_lenses:source.lenses.map(l=>({lens:l.slug,reason:'Yerel malzeme, ölçü, bakım ve kullanıcı rutini üzerinden ayrıca doğrulanmalıdır.'}))
  }
};

fs.writeFileSync(masterFile, `${JSON.stringify(master,null,2)}\n`);
console.log(`Türkçe admin Atlası oluşturuldu: ${master.lenses.length} yaklaşım, ${master.sources.length} kaynak, ${master.reference_registry.length} referans.`);
